Links and images
lostenderman/markdown pull request #140
Opened 2023-03-12 21:17 UTC by lostenderman

2023-03-13 22:35 UTC, Witiko requested changes

2023-03-13 22:35 UTC, Witiko commented on markdown.dtx
> +parsers.email_address = (parsers.alphanumeric + S(".!#$%&'*+/=?^_`{|}~-"))^1
``S(".!#$%&'*+/=?^_`{|}~-")`` seems to be a good candidate for getting a name.

2023-03-13 22:35 UTC, Witiko commented on markdown.dtx
> +                         - (parsers.lbracket + parsers.rbracket + parsers.blankline^2)))^1)
```suggestion
                        + parsers.inticks
                        + parsers.autolink
                        + ( parsers.backslash * parsers.backslash)
                        + ( parsers.backslash * (parsers.lbracket + parsers.rbracket)
                          + parsers.any
                          - (parsers.lbracket + parsers.rbracket + parsers.blankline^2)))^1)
```

2023-03-13 22:35 UTC, Witiko commented on markdown.dtx
>                                               - parsers.rparent))^1)
```suggestion
                    + -parsers.less
                    * Cs((parsers.inparens + ( parsers.anyescaped
                                             - parsers.spacing
                                             - parsers.rparent))^1)
```

2023-03-13 22:35 UTC, Witiko commented on markdown.dtx
> +                          / defer_link_and_image_processing
```suggestion
                           / defer_link_and_image_processing
```

2023-03-13 22:35 UTC, Witiko commented on markdown.dtx
As in #138, this is an extensive addition in a style quite foreign to the rest of the codebase. Can you please add a sentence or two of prose above each function, documenting what it does and what the purpose of the individual parameters is? We will need it soon enough when resolving merge conflicts between this pull request and https://github.com/Witiko/markdown/pull/256.

2023-03-20 09:22 UTC, Witiko commented on markdown.dtx
>                        * (parsers.any - parsers.spacing - parsers.less - parsers.more)^0
```suggestion
parsers.absolute_uri = parsers.autolink_scheme * parsers.colon
                     * (parsers.any - parsers.spacing - parsers.less - parsers.more)^0
```

2023-03-20 09:32 UTC, Witiko commented on markdown.dtx
>    local function resolve_inline_link_closer(t, index, include_bracket)
This is a definite improvement over not having any explanation, although I would still appreciate full-blown prose that can be typeset in the technical documentation and that allows you to describe the function in detail. For example, the following is preferable (here and everywhere):

```suggestion
%    \end{macrocode}
% \begin{markdown}
%
% Return the dangling parentheses of an inline link exactly as they were in the input.
%
% \end{markdown}
%  \begin{macrocode}
```

Keeping the description grounded in the actual parameters of the function is also appreciated. For example, you talk about "input" in your description, but the function accepts `t`, `index`, and `include_brackets` as parameters. The desciption should describe the intent of the function but also help the reader to understand what the parameters are.

2023-03-23 17:41 UTC, lostenderman commented
I suspect that the implementation of emphasis (and strong emphasis) will have to be merged with the implementation of links (and images) similarly to [this](https://spec.commonmark.org/0.30/#an-algorithm-for-parsing-nested-emphasis-and-links) essentially, because of these examples:

[522](https://spec.commonmark.org/0.30/#example-522):
```
*foo [bar* baz]
```

This is an emphasis because the link has no reference.

[533](https://spec.commonmark.org/0.30/#example-533):
```
*[foo*][ref]

[ref]: /uri
```

This is not an emphasis because the link has a reference.

Currently, only the second example would be parsed correctly. In the first one, no emphasis would be produced since the link is matched,  even though it does not produce a link.

2023-03-31 13:55 UTC, Witiko requested changes
I fixed some style issues and commented on a limitation that I am willing to merge but should be highlighted in the thesis. Overall, I am somewhat blind without CI, so I will leave more in-depth reading until https://github.com/Witiko/markdown/pull/226. Feel free to merge this (or any other) PR.

2023-03-31 13:55 UTC, Witiko commented on markdown.dtx
> +                  end, false)
```suggestion
  self.create_parser("parse_inlines_full_link_and_image",
                     function()
                       return parsers.inlines_full_link_and_image
                     end, false)
```

2023-03-31 13:55 UTC, Witiko commented on markdown.dtx
> +%  \begin{macrocode}
Same comment as https://github.com/lostenderman/markdown/pull/141/files#r1154487062.

2023-03-31 13:55 UTC, Witiko commented on markdown.dtx
> +                                            / process_links_and_images
```suggestion
      local LinkOrImageWithAttributes       = Ct(link_array) * Cc(link_group)
                                            / process_links_and_images
```

2023-04-01 08:04 UTC, merged